#ifndef VX3_CONF_H
#define VX3_CONF_H
// #define DEBUG_SOA  true
// #define DEBUG_SIMULATION_MANAGER true
// #define DEBUG_VOXEL_AND_LINK_VALUES true

#define VX3_VOXELYZE_KERNEL_ALLOCATE_FRAME_NUM      500

#define VX3_VOXELYZE_KERNEL_MAX_BATCH_SIZE          128
#define VX3_VOXELYZE_KERNEL_UPDATE_LINK_BLOCK_SIZE  128
#define VX3_VOXELYZE_KERNEL_UPDATE_VOXEL_BLOCK_SIZE 256

#define VX3_MATH_TREE_MAX_STACK_SIZE                4
#define VX3_MATH_TREE_MAX_EXPRESSION_TOKENS         16

#define VX3_RECORD_RESCALE                          1e-3

#endif